### ISSUE TITLE
docker 里  下载的 v2版本变的话

### ISSUE THREAD

**Issue by zhaozhejun** [fscarmen2/V2-for-Koyeb#6]
docker 里  下载的 v2版本变的话，，或者 entrypoint.sh  里  路径  不使用vmess/vless  ，，我测试无法连接通，，不知道什么问题。。

**Comment by fscarmen2** [comment]
应该是v2ray 4.5 版本以上的配置文件改了，所以本项目还是用旧的，建议用新项目

https://github.com/fscarmen2/Argo-X-Container-PaaS
